import { ReactElement } from "react";

import { BlogAnchor } from "@client/types/utils.type";

/**
 * Find the anchors in a blog post by MDX.
 *
 * @note About these types: just console.log() this value and see. MDX being not fully typed making
 * this section's typing quite bad, all filled with forced typecasts
 *
 * @param element The JSX element generated by running <Content />. Must be like that; this function
 * is not written and not tested for any general `JSX.Element`.
 */
export default function blogAnchors(element: JSX.Element): BlogAnchor[] {
    const contentChildren = element.props.children as (ReactElement | string)[];
    const headings = contentChildren.filter(
        node =>
            typeof node !== "string" &&
            typeof node.type === "string" &&
            ["h2", "h3"].includes(node.type)
    ) as ReactElement[];
    return headings.map(heading => ({
        level: heading.type as "h2" | "h3",
        id: heading.props.id,
        title: heading.props.children,
    }));
}
