name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      # Since CD on Vercel already builds the site for us, we only need to run linting here
      - run: npm run lint --workspace=packages/client
      - run: npm run test:ci --workspace=packages/client
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
