name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn
      # Since CD on Vercel already builds the site for us, we only need to run linting here
      - run: yarn lint
      - run: yarn test:client:ci
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  # Need to install firebase emulator, and how can we load env variable for testing?

  # test-backend:
  #   runs-on: ubuntu-lastest
  #   steps:
  #     - uses: action/checkout@v2
  #     - uses: action/setup-node@v2
  #       with:
  #         node-version: "16"
  #         cache: "yarn"
  #     - run: yarn
  #     - run: yarn emulate:test:server:ci
